"""Report rendering.

Tables are generated from `results.json`, never hand-written. That is the whole
point: a number in the README can be regenerated by anyone who runs the same
config, and a number that cannot be regenerated does not appear.

Rows are ordered by the primary metric so the table answers "what is best"
before it answers "what did you try".
"""

from __future__ import annotations

import json
import pathlib
from typing import Any

# Marker pair in README.md between which the generated table is written.
README_BEGIN = "<!-- BEGIN GENERATED TABLE -->"
README_END = "<!-- END GENERATED TABLE -->"


def load_results(path: str | pathlib.Path) -> dict[str, Any]:
    path = pathlib.Path(path)
    if path.is_dir():
        path = path / "results.json"
    return json.loads(path.read_text(encoding="utf-8"))


def render_markdown(payload: dict[str, Any]) -> str:
    """Render one markdown table per dataset, plus provenance and caveats."""
    config = payload.get("config", {})
    metrics: list[str] = config.get("metrics", [])
    primary = metrics[0] if metrics else None

    lines: list[str] = []
    ok_rows = [row for row in payload["results"] if row["status"] == "ok"]

    for dataset in dict.fromkeys(row["dataset"] for row in ok_rows):
        rows = [row for row in ok_rows if row["dataset"] == dataset]
        if primary:
            rows.sort(key=lambda row: row["metrics"].get(primary, 0.0), reverse=True)

        stats = payload.get("datasets", {}).get(dataset, {})
        caption = f"**{dataset}**"
        if stats:
            caption += (
                f" — {stats.get('documents', 0):,} documents, {stats.get('queries', 0):,} queries"
            )
        lines.append(caption)
        lines.append("")

        header = ["System", *metrics, "p50 ms", "p95 ms", "Index $", "$ / 1k queries"]
        lines.append("| " + " | ".join(header) + " |")
        lines.append("|" + "|".join(["---"] * len(header)) + "|")

        for row in rows:
            cells = [f"`{row['system']}`"]
            cells += [_fmt_metric(row["metrics"].get(metric)) for metric in metrics]
            cells.append(_fmt_ms(row["latency"].get("p50_ms")))
            cells.append(_fmt_ms(row["latency"].get("p95_ms")))
            cells.append(_fmt_usd(row["cost"].get("index_usd")))
            cells.append(_fmt_usd(row["cost"].get("usd_per_1k_queries")))
            lines.append("| " + " | ".join(cells) + " |")
        lines.append("")

    skipped = [row for row in payload["results"] if row["status"] == "skipped"]
    failed = [row for row in payload["results"] if row["status"] == "failed"]

    if skipped:
        lines.append("Skipped: " + _describe_rows(skipped))
        lines.append("")
    if failed:
        lines.append("**Failed:** " + _describe_rows(failed))
        lines.append("")

    if any(row["cost"].get("tokens_estimated") for row in ok_rows):
        lines.append(
            "Costs marked from estimated tokens use a characters-per-token "
            "heuristic where the provider returned no usage figure."
        )
        lines.append("")

    for warning in payload.get("warnings", []):
        lines.append(f"> Warning: {warning}")
    if payload.get("warnings"):
        lines.append("")

    environment = payload.get("environment", {})
    if environment:
        lines.append(
            f"Measured on {environment.get('platform', 'unknown')} "
            f"(Python {environment.get('python', '?')}). Latency is machine dependent; "
            "compare rows against each other, not against numbers from another machine."
        )

    return "\n".join(lines).rstrip() + "\n"


def _describe_rows(rows: list[dict[str, Any]]) -> str:
    """Render non-ok rows as `name` (reason), one entry per system."""
    return ", ".join(f"`{row['system']}` ({row['detail']})" for row in _unique(rows))


def _unique(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Collapse rows repeated across datasets to one entry per system."""
    seen: dict[str, dict[str, Any]] = {}
    for row in rows:
        seen.setdefault(row["system"], row)
    return list(seen.values())


def _fmt_metric(value: float | None) -> str:
    return "—" if value is None else f"{value:.4f}"


def _fmt_ms(value: float | None) -> str:
    return "—" if value is None else f"{value:.1f}"


def _fmt_usd(value: float | None) -> str:
    if value is None:
        return "—"
    if value == 0:
        return "$0"
    # Sub-cent figures are common and rounding them to two places turns a real
    # cost difference into a column of zeros.
    return f"${value:.4f}" if value < 1 else f"${value:,.2f}"


def write_readme_table(payload: dict[str, Any], readme: str | pathlib.Path) -> bool:
    """Replace the generated block in README.md. Returns False if no markers."""
    readme = pathlib.Path(readme)
    text = readme.read_text(encoding="utf-8")

    start = text.find(README_BEGIN)
    end = text.find(README_END)
    if start == -1 or end == -1 or end < start:
        return False

    table = render_markdown(payload)
    updated = text[: start + len(README_BEGIN)] + "\n\n" + table + "\n" + text[end:]
    readme.write_text(updated, encoding="utf-8")
    return True
